import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import SearchBar from "@/components/SearchBar";
import { Button } from "@/components/ui/button";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <div className="relative min-h-screen isolate overflow-hidden border-b  border-gray-200 bg-white">
                    <div className="mx-auto  mt-16 w-full max-w-2xl flex flex-col text-slate-900">
                        <SearchBar />
                        {children}
                    </div>
                </div>
            </body>
        </html>
    );
}
